### PR TITLE
collect defaults recursively

### PR DESCRIPTION
**Pull request by databasedav**
resolves https://github.com/slint-ui/document-features/issues/19

### CODE REVIEW

**Comment by databasedav** [comment]
can i remove `1.54.0` from the rust version matrix? also not sure about the crater ci error https://github.com/slint-ui/document-features/actions/runs/11755663862/job/32754124105?pr=28#step:5:137, since i still see the document-features flag here https://github.com/palfrey/serial_test/blob/3ac9744b019bee996c4d44afc72a0b1af8be1809/serial_test/Cargo.toml#L18

**Comment by ogoffart** [comment]
Thanks!

**Comment by databasedav** [comment]
@ogoffart please make a new release when you get the chance, thanks 🙏

**Comment by ogoffart** [comment]
done

**Pull request merged**
